### ISSUE TITLE
transparency issues

### ISSUE THREAD

**Issue by ajrothwell** [CityOfPhiladelphia/layerboard#11]
for some reason this service has transparency set to 40% in the actual service - http://services.arcgis.com/fLeGjb7u4uXqeF9q/arcgis/rest/services/Zoning_BaseDistricts/FeatureServer/0?token=4IgJ-MQgu7AgBcV-UEpKdEVLJNFdU1xX7c0dgtl0ts4Y8u4yT-8dHOWI6k8FXHiy3kaiVmoGnzv2y3_W-OEvdDEPEocF9o-juqbm7Ha_jRDpUoDFKTLLwubOU9CHYz48o9ZaFf_0wMqwEBOk037TllGKAwx-ARTVZBhGXlNIxUy41P2uhxQ6SVEO-SdufrigUIUV-Q62mTkcCyyRZ3KEhKL37PiPFt_UuKKlqj1YvQdP-eIslEnYR3lgYgsrO-Ni

it's hard to see that on that page, but control-F and start typing "transparency" and you'll see it says "transparency":40 in the middle of the drawing info section

that means every time zoning is turned on for the first time in openmaps.phila.gov, it comes on 60% opaque.  The opacity slider I put on there is starting at 100% opaque, because that's what the opacity is set in the webmap

So someone needs to re-upload this service with no transparency info in the service

I have written javascript to change the opacity to 100% when the layer loads in openmaps.phila.gov, but it is not working the first time the layer is turned on, even if I use $nextTick...

the other option is just to accept that it comes on at 60% opacity, and set it to that in the webmap too, so that my opacity slider starts in the same place

**Comment by phaedratinder** [comment]
Layer was republished at 100% opacity in accordance with wishes of Planning dept.
All other layers will retain transparency as set in published service and webmap will not alter this
